def deck() -> 'generator':
    """Функция которая создаёт упорядоченную колоду карт"""
    suits = ('черви', 'бубны', 'пики', 'трефы')
    for suit in suits:
        for num in range(2, 15):
            yield (num, suit)
            
cards = deck()

# >>> list(deck())[::13]
# [(2, 'черви'), (2, 'бубны'), (2, 'пики'), (2, 'трефы')]

# >>> cards.__next__()
# (2, 'черви')
# >>> cards.__next__()
# (3, 'черви')
# >>> cards.__next__()
# (4, 'черви')
# >>> cards.__next__()
# (5, 'черви')
# >>> cards.__next__()
# (6, 'черви')
# >>> cards.__next__()
# (7, 'черви')
# >>> cards.__next__()
# (8, 'черви')
# >>> cards.__next__()
# (9, 'черви')
# >>> cards.__next__()
# (10, 'черви')
# >>> cards.__next__()
# (11, 'черви')
# >>> cards.__next__()
# (12, 'черви')
# >>> cards.__next__()
# (13, 'черви')
# >>> cards.__next__()
# (14, 'черви')
# >>> cards.__next__()
# (2, 'бубны')
# >>> cards.__next__()
# (3, 'бубны')
# >>> cards.__next__()
# (4, 'бубны')
# >>> cards.__next__()
# (5, 'бубны')
# >>> cards.__next__()
# (6, 'бубны')
# >>> cards.__next__()
# (7, 'бубны')
# >>> cards.__next__()
# (8, 'бубны')
# >>> cards.__next__()
# (9, 'бубны')
# >>> cards.__next__()
# (10, 'бубны')
# >>> cards.__next__()
# (11, 'бубны')
# >>> cards.__next__()
# (12, 'бубны')
# >>> cards.__next__()
# (13, 'бубны')
# >>> cards.__next__()
# (14, 'бубны')
# >>> cards.__next__()
# (2, 'пики')
# >>> cards.__next__()
# (3, 'пики')
# >>> cards.__next__()
# (4, 'пики')
# >>> cards.__next__()
# (5, 'пики')
# >>> cards.__next__()
# (6, 'пики')
# >>> cards.__next__()
# (7, 'пики')
# >>> cards.__next__()
# (8, 'пики')
# >>> cards.__next__()
# (9, 'пики')
# >>> cards.__next__()
# (10, 'пики')
# >>> cards.__next__()
# (11, 'пики')
# >>> cards.__next__()
# (12, 'пики')
# >>> cards.__next__()
# (13, 'пики')
# >>> cards.__next__()
# (14, 'пики')
# >>> cards.__next__()
# (2, 'трефы')
# >>> cards.__next__()
# (3, 'трефы')
# >>> cards.__next__()
# (4, 'трефы')
# >>> cards.__next__()
# (5, 'трефы')
# >>> cards.__next__()
# (6, 'трефы')
# >>> cards.__next__()
# (7, 'трефы')
# >>> cards.__next__()
# (8, 'трефы')
# >>> cards.__next__()
# (9, 'трефы')
# >>> cards.__next__()
# (10, 'трефы')
# >>> cards.__next__()
# (11, 'трефы')
# >>> cards.__next__()
# (12, 'трефы')
# >>> cards.__next__()
# (13, 'трефы')
# >>> cards.__next__()
# (14, 'трефы')
# >>> cards.__next__()
# Traceback (most recent call last):
  # File "<stdin>", line 1, in <module>
# StopIteration